// Code generated by xorm reverse.
// 同步表结构到数据库
package dbmodel

import (
	"fmt"

	"xorm.io/xorm"
)

// InitSync 更新表结构到单库，用于测试和开发环境
// 快速同步表结构，以及dbdiff出表结构改动
func InitSync(orm *xorm.Engine) error {
	var err error

	err = sync(orm, &User{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &User error:%v", err))
	}
	err = sync(orm, &PowerGroup{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &PowerGroup error:%v", err))
	}
	err = sync(orm, &Project{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &Project error:%v", err))
	}
	err = sync(orm, &Power{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &Power error:%v", err))
	}
	err = sync(orm, &GmOrder{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &GmOrder error:%v", err))
	}
	err = sync(orm, &OperationLog{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &OperationLog error:%v", err))
	}
	err = sync(orm, &PowerAssignMent{})
	if err != nil {
		fmt.Print(fmt.Errorf("sync &PowerAssignMent error:%v", err))
	}

	return nil
}

// GetShardInfo 获取所有表的分区数量，大于1的都认为要分区
func GetShardInfo() map[string]DbTableInterface {
	info := make(map[string]DbTableInterface)

	info["user"] = new(User)
	info["power_group"] = new(PowerGroup)
	info["power"] = new(Power)
	info["project"] = new(Project)
	info["gm_order"] = new(GmOrder)
	info["operation_log"] = new(OperationLog)
	info["power_assign_ment"] = new(PowerAssignMent)

	return info
}

func sync(orm *xorm.Engine, table DbTableInterface) error {
	return orm.Sync2(table)
}
